// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type CatalogoFilmesProjetado struct {
	FilmID      int64     `db:"film_id"`
	Titulo      string    `db:"titulo"`
	Ano         *int32    `db:"ano"`
	Aplicacoes  int32     `db:"aplicacoes"`
	ProjetadoEm time.Time `db:"projetado_em"`
}

type Filme struct {
	ID           int64      `db:"id"`
	Titulo       string     `db:"titulo"`
	Ano          *int32     `db:"ano"`
	DuracaoMin   *int32     `db:"duracao_min"`
	Sinopse      *string    `db:"sinopse"`
	ImdbID       *string    `db:"imdb_id"`
	PosterUrl    *string    `db:"poster_url"`
	CriadoEm     time.Time  `db:"criado_em"`
	TmdbID       *int64     `db:"tmdb_id"`
	ArquivadoEm  *time.Time `db:"arquivado_em"`
	AtualizadoEm time.Time  `db:"atualizado_em"`
}
