// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogoFilmesProjetado struct {
	FilmID      int64              `db:"film_id"`
	Titulo      string             `db:"titulo"`
	Ano         *int32             `db:"ano"`
	Aplicacoes  int32              `db:"aplicacoes"`
	ProjetadoEm pgtype.Timestamptz `db:"projetado_em"`
}

type Film struct {
	ID        int64            `db:"id"`
	Title     string           `db:"title"`
	Year      *int32           `db:"year"`
	Runtime   *int32           `db:"runtime"`
	Synopsis  *string          `db:"synopsis"`
	ImdbID    *string          `db:"imdb_id"`
	PosterUrl *string          `db:"poster_url"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
}
