// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	BuscarFilmeProjetado(ctx context.Context, filmID int64) (CatalogoFilmesProjetado, error)
	GetFilm(ctx context.Context, id int64) (Film, error)
	// Usada por CreateFilm (RF02/task 0002): o subcomando CLI criar-filme insere o
	// filme e enfileira catalogo.filme_criado na mesma TX via outbox.Enqueue.
	// films.id é BIGINT sem identity/sequence (schema da migration 001); o próximo
	// id é calculado por MAX(id)+1 dentro do próprio statement — simplificação
	// aceitável para uma ferramenta de operador único (CLI, sem concorrência real);
	// colisão eventual é reportada como erro de constraint (exit code != 0 na CLI).
	InsertFilm(ctx context.Context, arg InsertFilmParams) (Film, error)
	ListFilms(ctx context.Context) ([]Film, error)
	// Projeção de catalogo.filme_criado (RF07, task 0005). Roda dentro da TX do
	// wrapper de dedup (outbox.ProcessarUmaVez): com dedup correto o conflito
	// nunca ocorre; se ocorrer, aplicacoes > 1 denuncia a falha (prova de RN01).
	UpsertFilmeProjetado(ctx context.Context, arg UpsertFilmeProjetadoParams) error
}

var _ Querier = (*Queries)(nil)
