// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Idempotente: reaplicar mantém a data original (COALESCE); 0 linhas = inexistente.
	ArquivarFilme(ctx context.Context, id int64) (int64, error)
	// Substitui os campos editáveis (RF03). tmdb_id não é editável à mão.
	AtualizarFilme(ctx context.Context, arg AtualizarFilmeParams) ([]AtualizarFilmeRow, error)
	BuscarFilmeProjetado(ctx context.Context, filmID int64) (CatalogoFilmesProjetado, error)
	// :many + LIMIT 1: ausência = vazio (domínio sem pgx.ErrNoRows).
	BuscarFilmePublico(ctx context.Context, id int64) ([]BuscarFilmePublicoRow, error)
	// id por IDENTITY (migration 007). Usada pelo backoffice e pela CLI na mesma
	// TX do evento catalogo.filme_criado (outbox).
	InserirFilme(ctx context.Context, arg InserirFilmeParams) (InserirFilmeRow, error)
	// Backoffice (RF03): inclui arquivados.
	ListarFilmesBackoffice(ctx context.Context) ([]ListarFilmesBackofficeRow, error)
	// Cartaz público (RF02 do PRD 0011): só não arquivados.
	ListarFilmesPublicos(ctx context.Context) ([]ListarFilmesPublicosRow, error)
	// Projeção de catalogo.filme_criado (RF07, task 0005). Roda dentro da TX do
	// wrapper de dedup (outbox.ProcessarUmaVez): com dedup correto o conflito
	// nunca ocorre; se ocorrer, aplicacoes > 1 denuncia a falha (prova de RN01).
	UpsertFilmeProjetado(ctx context.Context, arg UpsertFilmeProjetadoParams) error
}

var _ Querier = (*Queries)(nil)
