// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const arquivarFilme = `-- name: ArquivarFilme :execrows
UPDATE filmes
SET arquivado_em = COALESCE(arquivado_em, now()), atualizado_em = now()
WHERE id = $1
`

// Idempotente: reaplicar mantém a data original (COALESCE); 0 linhas = inexistente.
func (q *Queries) ArquivarFilme(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, arquivarFilme, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const atualizarFilme = `-- name: AtualizarFilme :many
UPDATE filmes
SET titulo = $2, sinopse = $3, duracao_min = $4, ano = $5,
    poster_url = $6, imdb_id = $7, atualizado_em = now()
WHERE id = $1
RETURNING id, titulo, sinopse, duracao_min, ano, poster_url, imdb_id, tmdb_id
`

type AtualizarFilmeParams struct {
	ID         int64   `db:"id"`
	Titulo     string  `db:"titulo"`
	Sinopse    *string `db:"sinopse"`
	DuracaoMin *int32  `db:"duracao_min"`
	Ano        *int32  `db:"ano"`
	PosterUrl  *string `db:"poster_url"`
	ImdbID     *string `db:"imdb_id"`
}

type AtualizarFilmeRow struct {
	ID         int64   `db:"id"`
	Titulo     string  `db:"titulo"`
	Sinopse    *string `db:"sinopse"`
	DuracaoMin *int32  `db:"duracao_min"`
	Ano        *int32  `db:"ano"`
	PosterUrl  *string `db:"poster_url"`
	ImdbID     *string `db:"imdb_id"`
	TmdbID     *int64  `db:"tmdb_id"`
}

// Substitui os campos editáveis (RF03). tmdb_id não é editável à mão.
func (q *Queries) AtualizarFilme(ctx context.Context, arg AtualizarFilmeParams) ([]AtualizarFilmeRow, error) {
	rows, err := q.db.Query(ctx, atualizarFilme,
		arg.ID,
		arg.Titulo,
		arg.Sinopse,
		arg.DuracaoMin,
		arg.Ano,
		arg.PosterUrl,
		arg.ImdbID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtualizarFilmeRow
	for rows.Next() {
		var i AtualizarFilmeRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Sinopse,
			&i.DuracaoMin,
			&i.Ano,
			&i.PosterUrl,
			&i.ImdbID,
			&i.TmdbID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarFilmeProjetado = `-- name: BuscarFilmeProjetado :one
SELECT film_id, titulo, ano, aplicacoes, projetado_em
FROM catalogo_filmes_projetados
WHERE film_id = $1
`

func (q *Queries) BuscarFilmeProjetado(ctx context.Context, filmID int64) (CatalogoFilmesProjetado, error) {
	row := q.db.QueryRow(ctx, buscarFilmeProjetado, filmID)
	var i CatalogoFilmesProjetado
	err := row.Scan(
		&i.FilmID,
		&i.Titulo,
		&i.Ano,
		&i.Aplicacoes,
		&i.ProjetadoEm,
	)
	return i, err
}

const buscarFilmePublico = `-- name: BuscarFilmePublico :many
SELECT id, titulo, sinopse, duracao_min, ano, poster_url, imdb_id, tmdb_id
FROM filmes
WHERE id = $1 AND arquivado_em IS NULL
LIMIT 1
`

type BuscarFilmePublicoRow struct {
	ID         int64   `db:"id"`
	Titulo     string  `db:"titulo"`
	Sinopse    *string `db:"sinopse"`
	DuracaoMin *int32  `db:"duracao_min"`
	Ano        *int32  `db:"ano"`
	PosterUrl  *string `db:"poster_url"`
	ImdbID     *string `db:"imdb_id"`
	TmdbID     *int64  `db:"tmdb_id"`
}

// :many + LIMIT 1: ausência = vazio (domínio sem pgx.ErrNoRows).
func (q *Queries) BuscarFilmePublico(ctx context.Context, id int64) ([]BuscarFilmePublicoRow, error) {
	rows, err := q.db.Query(ctx, buscarFilmePublico, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarFilmePublicoRow
	for rows.Next() {
		var i BuscarFilmePublicoRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Sinopse,
			&i.DuracaoMin,
			&i.Ano,
			&i.PosterUrl,
			&i.ImdbID,
			&i.TmdbID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inserirFilme = `-- name: InserirFilme :one
INSERT INTO filmes (titulo, sinopse, duracao_min, ano, poster_url, imdb_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, titulo, sinopse, duracao_min, ano, poster_url, imdb_id, tmdb_id
`

type InserirFilmeParams struct {
	Titulo     string  `db:"titulo"`
	Sinopse    *string `db:"sinopse"`
	DuracaoMin *int32  `db:"duracao_min"`
	Ano        *int32  `db:"ano"`
	PosterUrl  *string `db:"poster_url"`
	ImdbID     *string `db:"imdb_id"`
}

type InserirFilmeRow struct {
	ID         int64   `db:"id"`
	Titulo     string  `db:"titulo"`
	Sinopse    *string `db:"sinopse"`
	DuracaoMin *int32  `db:"duracao_min"`
	Ano        *int32  `db:"ano"`
	PosterUrl  *string `db:"poster_url"`
	ImdbID     *string `db:"imdb_id"`
	TmdbID     *int64  `db:"tmdb_id"`
}

// id por IDENTITY (migration 007). Usada pelo backoffice e pela CLI na mesma
// TX do evento catalogo.filme_criado (outbox).
func (q *Queries) InserirFilme(ctx context.Context, arg InserirFilmeParams) (InserirFilmeRow, error) {
	row := q.db.QueryRow(ctx, inserirFilme,
		arg.Titulo,
		arg.Sinopse,
		arg.DuracaoMin,
		arg.Ano,
		arg.PosterUrl,
		arg.ImdbID,
	)
	var i InserirFilmeRow
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Sinopse,
		&i.DuracaoMin,
		&i.Ano,
		&i.PosterUrl,
		&i.ImdbID,
		&i.TmdbID,
	)
	return i, err
}

const listarFilmesBackoffice = `-- name: ListarFilmesBackoffice :many
SELECT id, titulo, sinopse, duracao_min, ano, poster_url, imdb_id, tmdb_id, arquivado_em
FROM filmes
ORDER BY criado_em DESC, id DESC
LIMIT 500
`

type ListarFilmesBackofficeRow struct {
	ID          int64      `db:"id"`
	Titulo      string     `db:"titulo"`
	Sinopse     *string    `db:"sinopse"`
	DuracaoMin  *int32     `db:"duracao_min"`
	Ano         *int32     `db:"ano"`
	PosterUrl   *string    `db:"poster_url"`
	ImdbID      *string    `db:"imdb_id"`
	TmdbID      *int64     `db:"tmdb_id"`
	ArquivadoEm *time.Time `db:"arquivado_em"`
}

// Backoffice (RF03): inclui arquivados.
func (q *Queries) ListarFilmesBackoffice(ctx context.Context) ([]ListarFilmesBackofficeRow, error) {
	rows, err := q.db.Query(ctx, listarFilmesBackoffice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarFilmesBackofficeRow
	for rows.Next() {
		var i ListarFilmesBackofficeRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Sinopse,
			&i.DuracaoMin,
			&i.Ano,
			&i.PosterUrl,
			&i.ImdbID,
			&i.TmdbID,
			&i.ArquivadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarFilmesPublicos = `-- name: ListarFilmesPublicos :many
SELECT id, titulo, sinopse, duracao_min, ano, poster_url, imdb_id, tmdb_id
FROM filmes
WHERE arquivado_em IS NULL
ORDER BY criado_em DESC, id DESC
LIMIT 100
`

type ListarFilmesPublicosRow struct {
	ID         int64   `db:"id"`
	Titulo     string  `db:"titulo"`
	Sinopse    *string `db:"sinopse"`
	DuracaoMin *int32  `db:"duracao_min"`
	Ano        *int32  `db:"ano"`
	PosterUrl  *string `db:"poster_url"`
	ImdbID     *string `db:"imdb_id"`
	TmdbID     *int64  `db:"tmdb_id"`
}

// Cartaz público (RF02 do PRD 0011): só não arquivados.
func (q *Queries) ListarFilmesPublicos(ctx context.Context) ([]ListarFilmesPublicosRow, error) {
	rows, err := q.db.Query(ctx, listarFilmesPublicos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarFilmesPublicosRow
	for rows.Next() {
		var i ListarFilmesPublicosRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Sinopse,
			&i.DuracaoMin,
			&i.Ano,
			&i.PosterUrl,
			&i.ImdbID,
			&i.TmdbID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFilmeProjetado = `-- name: UpsertFilmeProjetado :exec
INSERT INTO catalogo_filmes_projetados (film_id, titulo, ano)
VALUES ($1, $2, $3)
ON CONFLICT (film_id) DO UPDATE
SET titulo       = EXCLUDED.titulo,
    ano          = EXCLUDED.ano,
    aplicacoes   = catalogo_filmes_projetados.aplicacoes + 1,
    projetado_em = now()
`

type UpsertFilmeProjetadoParams struct {
	FilmID int64  `db:"film_id"`
	Titulo string `db:"titulo"`
	Ano    *int32 `db:"ano"`
}

// Projeção de catalogo.filme_criado (RF07, task 0005). Roda dentro da TX do
// wrapper de dedup (outbox.ProcessarUmaVez): com dedup correto o conflito
// nunca ocorre; se ocorrer, aplicacoes > 1 denuncia a falha (prova de RN01).
func (q *Queries) UpsertFilmeProjetado(ctx context.Context, arg UpsertFilmeProjetadoParams) error {
	_, err := q.db.Exec(ctx, upsertFilmeProjetado, arg.FilmID, arg.Titulo, arg.Ano)
	return err
}

const upsertFilmeTMDB = `-- name: UpsertFilmeTMDB :one
INSERT INTO filmes (tmdb_id, titulo, sinopse, duracao_min, ano, poster_url, imdb_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tmdb_id) DO UPDATE
SET titulo = EXCLUDED.titulo,
    sinopse = EXCLUDED.sinopse,
    duracao_min = EXCLUDED.duracao_min,
    ano = EXCLUDED.ano,
    poster_url = EXCLUDED.poster_url,
    imdb_id = EXCLUDED.imdb_id,
    atualizado_em = now()
RETURNING id, titulo, sinopse, duracao_min, ano, poster_url, imdb_id, tmdb_id, (xmax = 0) AS inserido
`

type UpsertFilmeTMDBParams struct {
	TmdbID     *int64  `db:"tmdb_id"`
	Titulo     string  `db:"titulo"`
	Sinopse    *string `db:"sinopse"`
	DuracaoMin *int32  `db:"duracao_min"`
	Ano        *int32  `db:"ano"`
	PosterUrl  *string `db:"poster_url"`
	ImdbID     *string `db:"imdb_id"`
}

type UpsertFilmeTMDBRow struct {
	ID         int64   `db:"id"`
	Titulo     string  `db:"titulo"`
	Sinopse    *string `db:"sinopse"`
	DuracaoMin *int32  `db:"duracao_min"`
	Ano        *int32  `db:"ano"`
	PosterUrl  *string `db:"poster_url"`
	ImdbID     *string `db:"imdb_id"`
	TmdbID     *int64  `db:"tmdb_id"`
	Inserido   bool    `db:"inserido"`
}

// Importação do TMDB (PRD 0012 RF03): idempotente por tmdb_id (UNIQUE da
// 007). Reimportar atualiza os dados mas NÃO desarquiva. inserido = true só
// na criação (xmax = 0 na linha nova) — o evento só é emitido nesse caso.
func (q *Queries) UpsertFilmeTMDB(ctx context.Context, arg UpsertFilmeTMDBParams) (UpsertFilmeTMDBRow, error) {
	row := q.db.QueryRow(ctx, upsertFilmeTMDB,
		arg.TmdbID,
		arg.Titulo,
		arg.Sinopse,
		arg.DuracaoMin,
		arg.Ano,
		arg.PosterUrl,
		arg.ImdbID,
	)
	var i UpsertFilmeTMDBRow
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Sinopse,
		&i.DuracaoMin,
		&i.Ano,
		&i.PosterUrl,
		&i.ImdbID,
		&i.TmdbID,
		&i.Inserido,
	)
	return i, err
}
