// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Usuario struct {
	ID           uuid.UUID          `db:"id"`
	Nome         string             `db:"nome"`
	Email        string             `db:"email"`
	SenhaHash    string             `db:"senha_hash"`
	Papel        string             `db:"papel"`
	CriadoEm     pgtype.Timestamptz `db:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `db:"atualizado_em"`
}
