// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const buscarUsuarioPorEmail = `-- name: BuscarUsuarioPorEmail :many
SELECT id, nome, email, senha_hash, papel
FROM usuario
WHERE email = $1
LIMIT 1
`

type BuscarUsuarioPorEmailRow struct {
	ID        uuid.UUID `db:"id"`
	Nome      string    `db:"nome"`
	Email     string    `db:"email"`
	SenhaHash string    `db:"senha_hash"`
	Papel     string    `db:"papel"`
}

// :many + LIMIT 1 em vez de :one: ausência = slice vazio (sem pgx.ErrNoRows
// no domínio — RNF01 do PRD 0009).
func (q *Queries) BuscarUsuarioPorEmail(ctx context.Context, email string) ([]BuscarUsuarioPorEmailRow, error) {
	rows, err := q.db.Query(ctx, buscarUsuarioPorEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarUsuarioPorEmailRow
	for rows.Next() {
		var i BuscarUsuarioPorEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Email,
			&i.SenhaHash,
			&i.Papel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarUsuarioPorID = `-- name: BuscarUsuarioPorID :many
SELECT id, nome, email, papel
FROM usuario
WHERE id = $1
LIMIT 1
`

type BuscarUsuarioPorIDRow struct {
	ID    uuid.UUID `db:"id"`
	Nome  string    `db:"nome"`
	Email string    `db:"email"`
	Papel string    `db:"papel"`
}

func (q *Queries) BuscarUsuarioPorID(ctx context.Context, id uuid.UUID) ([]BuscarUsuarioPorIDRow, error) {
	rows, err := q.db.Query(ctx, buscarUsuarioPorID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarUsuarioPorIDRow
	for rows.Next() {
		var i BuscarUsuarioPorIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Email,
			&i.Papel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inserirUsuario = `-- name: InserirUsuario :execrows
INSERT INTO usuario (id, nome, email, senha_hash, papel)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (email) DO NOTHING
`

type InserirUsuarioParams struct {
	ID        uuid.UUID `db:"id"`
	Nome      string    `db:"nome"`
	Email     string    `db:"email"`
	SenhaHash string    `db:"senha_hash"`
	Papel     string    `db:"papel"`
}

// Registro/seed (task 0009). ON CONFLICT em vez de erro de constraint: 0
// linhas = e-mail em uso, sem o domínio depender do tipo de erro do driver.
func (q *Queries) InserirUsuario(ctx context.Context, arg InserirUsuarioParams) (int64, error) {
	result, err := q.db.Exec(ctx, inserirUsuario,
		arg.ID,
		arg.Nome,
		arg.Email,
		arg.SenhaHash,
		arg.Papel,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
