// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contarPendentes = `-- name: ContarPendentes :one
SELECT count(*) FROM outbox_events WHERE published_at IS NULL
`

func (q *Queries) ContarPendentes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarPendentes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const idadePendenteMaisAntigo = `-- name: IdadePendenteMaisAntigo :one
SELECT COALESCE(EXTRACT(EPOCH FROM now() - min(created_at)), 0)::float8 AS idade_segundos
FROM outbox_events
WHERE published_at IS NULL
`

// Lag do relay (RF04 do PRD 0006): idade em segundos do evento pendente mais
// antigo; 0 quando não há pendentes. Usa o índice parcial de pendentes (002).
func (q *Queries) IdadePendenteMaisAntigo(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, idadePendenteMaisAntigo)
	var idade_segundos float64
	err := row.Scan(&idade_segundos)
	return idade_segundos, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO outbox_events (event_type, aggregate_id, occurred_at, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, event_type, aggregate_id, occurred_at, payload, created_at, published_at
`

type InsertEventParams struct {
	EventType   string             `db:"event_type"`
	AggregateID string             `db:"aggregate_id"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at"`
	Payload     []byte             `db:"payload"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.EventType,
		arg.AggregateID,
		arg.OccurredAt,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateID,
		&i.OccurredAt,
		&i.Payload,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const marcarPublicado = `-- name: MarcarPublicado :exec
UPDATE outbox_events
SET published_at = $2
WHERE id = $1
`

type MarcarPublicadoParams struct {
	ID          pgtype.UUID        `db:"id"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
}

func (q *Queries) MarcarPublicado(ctx context.Context, arg MarcarPublicadoParams) error {
	_, err := q.db.Exec(ctx, marcarPublicado, arg.ID, arg.PublishedAt)
	return err
}

const registrarProcessada = `-- name: RegistrarProcessada :execrows
INSERT INTO processed_messages (message_id, consumidor)
VALUES ($1, $2)
ON CONFLICT (message_id, consumidor) DO NOTHING
`

type RegistrarProcessadaParams struct {
	MessageID  pgtype.UUID `db:"message_id"`
	Consumidor string      `db:"consumidor"`
}

// Dedup do consumidor idempotente (RF05, task 0005): executada na MESMA TX do
// efeito de domínio. 0 linhas afetadas = message_id já processado por este
// consumidor (duplicata) — o efeito não roda. Uma entrega concorrente com o
// mesmo message_id bloqueia na PK até a primeira TX terminar.
func (q *Queries) RegistrarProcessada(ctx context.Context, arg RegistrarProcessadaParams) (int64, error) {
	result, err := q.db.Exec(ctx, registrarProcessada, arg.MessageID, arg.Consumidor)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectPendentesParaPublicar = `-- name: SelectPendentesParaPublicar :many
SELECT id, event_type, aggregate_id, occurred_at, payload, created_at, published_at
FROM outbox_events
WHERE published_at IS NULL
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Lote de eventos ainda não publicados, travados para esta transação
// (SKIP LOCKED deixa outras instâncias do relay pularem linhas já em processamento
// em vez de bloquear — RF03/ADR 0007).
func (q *Queries) SelectPendentesParaPublicar(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, selectPendentesParaPublicar, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.OccurredAt,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
