// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Ingresso struct {
	ID            uuid.UUID `db:"id"`
	PedidoID      uuid.UUID `db:"pedido_id"`
	SessaoID      int64     `db:"sessao_id"`
	AssentoCodigo string    `db:"assento_codigo"`
	Status        string    `db:"status"`
	VersaoToken   int16     `db:"versao_token"`
	CriadoEm      time.Time `db:"criado_em"`
}

type Pedido struct {
	ID                uuid.UUID  `db:"id"`
	Codigo            string     `db:"codigo"`
	Email             string     `db:"email"`
	UsuarioID         *uuid.UUID `db:"usuario_id"`
	DonoHash          []byte     `db:"dono_hash"`
	SessaoID          int64      `db:"sessao_id"`
	Assentos          []string   `db:"assentos"`
	TotalCentavos     int64      `db:"total_centavos"`
	Status            string     `db:"status"`
	ExpiraEm          time.Time  `db:"expira_em"`
	PaymentIntentID   *string    `db:"payment_intent_id"`
	MotivoEstorno     *string    `db:"motivo_estorno"`
	TentativasEstorno int16      `db:"tentativas_estorno"`
	CriadoEm          time.Time  `db:"criado_em"`
	AtualizadoEm      time.Time  `db:"atualizado_em"`
	CobrancaEncerrada bool       `db:"cobranca_encerrada"`
}

type PedidoEvento struct {
	ID         int64     `db:"id"`
	PedidoID   uuid.UUID `db:"pedido_id"`
	De         *string   `db:"de"`
	Para       string    `db:"para"`
	OcorridoEm time.Time `db:"ocorrido_em"`
}

type StripeEvento struct {
	EventID    string    `db:"event_id"`
	Tipo       string    `db:"tipo"`
	RecebidoEm time.Time `db:"recebido_em"`
}
