// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const buscarPedidoDoDono = `-- name: BuscarPedidoDoDono :many
SELECT id, codigo, sessao_id, assentos::text[] AS assentos, total_centavos, status, expira_em
FROM pedidos
WHERE id = $1
  AND (dono_hash = $2 OR ($3::uuid IS NOT NULL AND usuario_id = $3::uuid))
`

type BuscarPedidoDoDonoParams struct {
	ID        uuid.UUID  `db:"id"`
	DonoHash  []byte     `db:"dono_hash"`
	UsuarioID *uuid.UUID `db:"usuario_id"`
}

type BuscarPedidoDoDonoRow struct {
	ID            uuid.UUID `db:"id"`
	Codigo        string    `db:"codigo"`
	SessaoID      int64     `db:"sessao_id"`
	Assentos      []string  `db:"assentos"`
	TotalCentavos int64     `db:"total_centavos"`
	Status        string    `db:"status"`
	ExpiraEm      time.Time `db:"expira_em"`
}

// Posse (RF06 da 0023; PRD 0031): o carrinho que criou o pedido OU a conta
// vinculada a ele (usuario_id vem só do JWT).
func (q *Queries) BuscarPedidoDoDono(ctx context.Context, arg BuscarPedidoDoDonoParams) ([]BuscarPedidoDoDonoRow, error) {
	rows, err := q.db.Query(ctx, buscarPedidoDoDono, arg.ID, arg.DonoHash, arg.UsuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarPedidoDoDonoRow
	for rows.Next() {
		var i BuscarPedidoDoDonoRow
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.SessaoID,
			&i.Assentos,
			&i.TotalCentavos,
			&i.Status,
			&i.ExpiraEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelarIngressosDoPedido = `-- name: CancelarIngressosDoPedido :execrows
UPDATE ingressos SET status = 'cancelado'
WHERE pedido_id = $1 AND status = 'ativo'
`

// Ingressos invalidados na TX do cancelamento (ADR 0011): o /i/* vira 410.
func (q *Queries) CancelarIngressosDoPedido(ctx context.Context, pedidoID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelarIngressosDoPedido, pedidoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const contarPresos = `-- name: ContarPresos :one
SELECT
    count(*) FILTER (WHERE status = 'aguardando_pagamento' AND expira_em <= $1)::bigint AS aguardando_vencido,
    count(*) FILTER (WHERE status = 'estorno_pendente')::bigint AS estorno_pendente
FROM pedidos
WHERE status IN ('aguardando_pagamento', 'estorno_pendente')
`

type ContarPresosRow struct {
	AguardandoVencido int64 `db:"aguardando_vencido"`
	EstornoPendente   int64 `db:"estorno_pendente"`
}

// Gauge pedidos_presos (PRD 0026): vencidos além da margem do hold (a
// reconciliação deveria tê-los resolvido) e estornos ainda pendentes.
func (q *Queries) ContarPresos(ctx context.Context, limiteVencido time.Time) (ContarPresosRow, error) {
	row := q.db.QueryRow(ctx, contarPresos, limiteVencido)
	var i ContarPresosRow
	err := row.Scan(&i.AguardandoVencido, &i.EstornoPendente)
	return i, err
}

const definirCobranca = `-- name: DefinirCobranca :execrows
UPDATE pedidos
SET payment_intent_id = $1, atualizado_em = $2
WHERE id = $3 AND payment_intent_id IS NULL
`

type DefinirCobrancaParams struct {
	PaymentIntentID *string   `db:"payment_intent_id"`
	Agora           time.Time `db:"agora"`
	ID              uuid.UUID `db:"id"`
}

// Grava o id da cobrança uma única vez. Sem filtro de status: o pivô também
// recupera a cobrança órfã (gateway respondeu, mas a gravação falhou) de um
// pedido já expirado, que precisa dela para o estorno (auditoria 0023).
func (q *Queries) DefinirCobranca(ctx context.Context, arg DefinirCobrancaParams) (int64, error) {
	result, err := q.db.Exec(ctx, definirCobranca, arg.PaymentIntentID, arg.Agora, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const emitirIngresso = `-- name: EmitirIngresso :many
INSERT INTO ingressos (id, pedido_id, sessao_id, assento_codigo, status, versao_token, criado_em)
VALUES ($1, $2, $3, $4, 'ativo', 1, $5)
ON CONFLICT (sessao_id, assento_codigo) WHERE status = 'ativo' DO NOTHING
RETURNING id
`

type EmitirIngressoParams struct {
	ID            uuid.UUID `db:"id"`
	PedidoID      uuid.UUID `db:"pedido_id"`
	SessaoID      int64     `db:"sessao_id"`
	AssentoCodigo string    `db:"assento_codigo"`
	Agora         time.Time `db:"agora"`
}

// Segunda linha de defesa: sem linha = o assento já tem ingresso ativo.
func (q *Queries) EmitirIngresso(ctx context.Context, arg EmitirIngressoParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, emitirIngresso,
		arg.ID,
		arg.PedidoID,
		arg.SessaoID,
		arg.AssentoCodigo,
		arg.Agora,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const encerrarCobranca = `-- name: EncerrarCobranca :exec
UPDATE pedidos SET cobranca_encerrada = true WHERE id = $1
`

// A cobrança do pedido foi cancelada no gateway (ou já estava): nada a varrer.
func (q *Queries) EncerrarCobranca(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, encerrarCobranca, id)
	return err
}

const estornosPendentes = `-- name: EstornosPendentes :many
SELECT id, payment_intent_id, tentativas_estorno, atualizado_em, motivo_estorno
FROM pedidos
WHERE status = 'estorno_pendente'
ORDER BY atualizado_em
LIMIT $1::int
`

type EstornosPendentesRow struct {
	ID                uuid.UUID `db:"id"`
	PaymentIntentID   *string   `db:"payment_intent_id"`
	TentativasEstorno int16     `db:"tentativas_estorno"`
	AtualizadoEm      time.Time `db:"atualizado_em"`
	MotivoEstorno     *string   `db:"motivo_estorno"`
}

// Job de estorno (PRD 0025): o backoff por tentativas é aplicado no serviço.
func (q *Queries) EstornosPendentes(ctx context.Context, limite int32) ([]EstornosPendentesRow, error) {
	rows, err := q.db.Query(ctx, estornosPendentes, limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EstornosPendentesRow
	for rows.Next() {
		var i EstornosPendentesRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentIntentID,
			&i.TentativasEstorno,
			&i.AtualizadoEm,
			&i.MotivoEstorno,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventosDoPedido = `-- name: EventosDoPedido :many
SELECT de, para, ocorrido_em
FROM pedido_eventos
WHERE pedido_id = $1
ORDER BY id
`

type EventosDoPedidoRow struct {
	De         *string   `db:"de"`
	Para       string    `db:"para"`
	OcorridoEm time.Time `db:"ocorrido_em"`
}

func (q *Queries) EventosDoPedido(ctx context.Context, pedidoID uuid.UUID) ([]EventosDoPedidoRow, error) {
	rows, err := q.db.Query(ctx, eventosDoPedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventosDoPedidoRow
	for rows.Next() {
		var i EventosDoPedidoRow
		if err := rows.Scan(&i.De, &i.Para, &i.OcorridoEm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiradosComCobrancaAberta = `-- name: ExpiradosComCobrancaAberta :many
SELECT id, payment_intent_id
FROM pedidos
WHERE status = 'expirado' AND NOT cobranca_encerrada AND payment_intent_id IS NOT NULL
ORDER BY atualizado_em
LIMIT $1::int
`

type ExpiradosComCobrancaAbertaRow struct {
	ID              uuid.UUID `db:"id"`
	PaymentIntentID *string   `db:"payment_intent_id"`
}

// Varredura (PRD 0027): expirados cuja cobrança não foi encerrada — o
// cancelamento pode ter sido recusado porque o cliente acabou de pagar.
func (q *Queries) ExpiradosComCobrancaAberta(ctx context.Context, limite int32) ([]ExpiradosComCobrancaAbertaRow, error) {
	rows, err := q.db.Query(ctx, expiradosComCobrancaAberta, limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpiradosComCobrancaAbertaRow
	for rows.Next() {
		var i ExpiradosComCobrancaAbertaRow
		if err := rows.Scan(&i.ID, &i.PaymentIntentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ingressoParaPagina = `-- name: IngressoParaPagina :many
SELECT i.assento_codigo, i.status, i.versao_token, i.sessao_id, p.status AS status_pedido
FROM ingressos i
JOIN pedidos p ON p.id = i.pedido_id
WHERE i.id = $1
`

type IngressoParaPaginaRow struct {
	AssentoCodigo string `db:"assento_codigo"`
	Status        string `db:"status"`
	VersaoToken   int16  `db:"versao_token"`
	SessaoID      int64  `db:"sessao_id"`
	StatusPedido  string `db:"status_pedido"`
}

// Página pública do ingresso (PRD 0034): o HMAC é conferido no serviço.
func (q *Queries) IngressoParaPagina(ctx context.Context, id uuid.UUID) ([]IngressoParaPaginaRow, error) {
	rows, err := q.db.Query(ctx, ingressoParaPagina, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngressoParaPaginaRow
	for rows.Next() {
		var i IngressoParaPaginaRow
		if err := rows.Scan(
			&i.AssentoCodigo,
			&i.Status,
			&i.VersaoToken,
			&i.SessaoID,
			&i.StatusPedido,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ingressosAtivosDoPedido = `-- name: IngressosAtivosDoPedido :many
SELECT id, assento_codigo, versao_token
FROM ingressos
WHERE pedido_id = $1 AND status = 'ativo'
ORDER BY assento_codigo
`

type IngressosAtivosDoPedidoRow struct {
	ID            uuid.UUID `db:"id"`
	AssentoCodigo string    `db:"assento_codigo"`
	VersaoToken   int16     `db:"versao_token"`
}

func (q *Queries) IngressosAtivosDoPedido(ctx context.Context, pedidoID uuid.UUID) ([]IngressosAtivosDoPedidoRow, error) {
	rows, err := q.db.Query(ctx, ingressosAtivosDoPedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngressosAtivosDoPedidoRow
	for rows.Next() {
		var i IngressosAtivosDoPedidoRow
		if err := rows.Scan(&i.ID, &i.AssentoCodigo, &i.VersaoToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ingressosDoPedido = `-- name: IngressosDoPedido :many
SELECT assento_codigo, status
FROM ingressos
WHERE pedido_id = $1
ORDER BY assento_codigo
`

type IngressosDoPedidoRow struct {
	AssentoCodigo string `db:"assento_codigo"`
	Status        string `db:"status"`
}

func (q *Queries) IngressosDoPedido(ctx context.Context, pedidoID uuid.UUID) ([]IngressosDoPedidoRow, error) {
	rows, err := q.db.Query(ctx, ingressosDoPedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngressosDoPedidoRow
	for rows.Next() {
		var i IngressosDoPedidoRow
		if err := rows.Scan(&i.AssentoCodigo, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inserirPedido = `-- name: InserirPedido :many
INSERT INTO pedidos (id, codigo, email, usuario_id, dono_hash, sessao_id, assentos, total_centavos, status, expira_em, criado_em, atualizado_em)
VALUES ($1, $2, $3, $4, $5, $6, $7::varchar[], $8, 'aguardando_pagamento', $9, $10, $10)
ON CONFLICT (dono_hash) WHERE status = 'aguardando_pagamento' DO NOTHING
RETURNING id
`

type InserirPedidoParams struct {
	ID            uuid.UUID  `db:"id"`
	Codigo        string     `db:"codigo"`
	Email         string     `db:"email"`
	UsuarioID     *uuid.UUID `db:"usuario_id"`
	DonoHash      []byte     `db:"dono_hash"`
	SessaoID      int64      `db:"sessao_id"`
	Assentos      []string   `db:"assentos"`
	TotalCentavos int64      `db:"total_centavos"`
	ExpiraEm      time.Time  `db:"expira_em"`
	Agora         time.Time  `db:"agora"`
}

// Sem linha no RETURNING = o carrinho já tem pedido pendente (índice único
// parcial pedidos_pendente_por_dono) — decidido pelo banco, sem pré-check.
func (q *Queries) InserirPedido(ctx context.Context, arg InserirPedidoParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, inserirPedido,
		arg.ID,
		arg.Codigo,
		arg.Email,
		arg.UsuarioID,
		arg.DonoHash,
		arg.SessaoID,
		arg.Assentos,
		arg.TotalCentavos,
		arg.ExpiraEm,
		arg.Agora,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidosDoUsuario = `-- name: ListarPedidosDoUsuario :many
SELECT id, codigo, sessao_id, assentos::text[] AS assentos, total_centavos, status, expira_em
FROM pedidos
WHERE usuario_id = $1
ORDER BY criado_em DESC
LIMIT $3::int OFFSET $2::int
`

type ListarPedidosDoUsuarioParams struct {
	UsuarioID    *uuid.UUID `db:"usuario_id"`
	Deslocamento int32      `db:"deslocamento"`
	Limite       int32      `db:"limite"`
}

type ListarPedidosDoUsuarioRow struct {
	ID            uuid.UUID `db:"id"`
	Codigo        string    `db:"codigo"`
	SessaoID      int64     `db:"sessao_id"`
	Assentos      []string  `db:"assentos"`
	TotalCentavos int64     `db:"total_centavos"`
	Status        string    `db:"status"`
	ExpiraEm      time.Time `db:"expira_em"`
}

// "Meus pedidos" (PRD 0031): mais recentes primeiro, paginado.
func (q *Queries) ListarPedidosDoUsuario(ctx context.Context, arg ListarPedidosDoUsuarioParams) ([]ListarPedidosDoUsuarioRow, error) {
	rows, err := q.db.Query(ctx, listarPedidosDoUsuario, arg.UsuarioID, arg.Deslocamento, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPedidosDoUsuarioRow
	for rows.Next() {
		var i ListarPedidosDoUsuarioRow
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.SessaoID,
			&i.Assentos,
			&i.TotalCentavos,
			&i.Status,
			&i.ExpiraEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidosOperador = `-- name: ListarPedidosOperador :many
SELECT id, sessao_id, email, assentos::text[] AS assentos, total_centavos, status, motivo_estorno, criado_em
FROM pedidos
WHERE ($1::bigint IS NULL OR sessao_id = $1::bigint)
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY criado_em DESC, id
LIMIT $4::int OFFSET $3::int
`

type ListarPedidosOperadorParams struct {
	SessaoID     *int64  `db:"sessao_id"`
	Status       *string `db:"status"`
	Deslocamento int32   `db:"deslocamento"`
	Limite       int32   `db:"limite"`
}

type ListarPedidosOperadorRow struct {
	ID            uuid.UUID `db:"id"`
	SessaoID      int64     `db:"sessao_id"`
	Email         string    `db:"email"`
	Assentos      []string  `db:"assentos"`
	TotalCentavos int64     `db:"total_centavos"`
	Status        string    `db:"status"`
	MotivoEstorno *string   `db:"motivo_estorno"`
	CriadoEm      time.Time `db:"criado_em"`
}

// Backoffice (PRD 0037): filtros opcionais por sessão e status, mais recentes
// primeiro, paginado. Nunca devolve o código (credencial do convidado).
func (q *Queries) ListarPedidosOperador(ctx context.Context, arg ListarPedidosOperadorParams) ([]ListarPedidosOperadorRow, error) {
	rows, err := q.db.Query(ctx, listarPedidosOperador,
		arg.SessaoID,
		arg.Status,
		arg.Deslocamento,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPedidosOperadorRow
	for rows.Next() {
		var i ListarPedidosOperadorRow
		if err := rows.Scan(
			&i.ID,
			&i.SessaoID,
			&i.Email,
			&i.Assentos,
			&i.TotalCentavos,
			&i.Status,
			&i.MotivoEstorno,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarEstorno = `-- name: MarcarEstorno :execrows
UPDATE pedidos
SET status = 'estorno_pendente', motivo_estorno = $1, atualizado_em = $2
WHERE id = $3 AND status = $4
`

type MarcarEstornoParams struct {
	Motivo *string   `db:"motivo"`
	Agora  time.Time `db:"agora"`
	ID     uuid.UUID `db:"id"`
	De     string    `db:"de"`
}

// CAS para estorno_pendente, registrando o motivo (ADR 0010/0011).
func (q *Queries) MarcarEstorno(ctx context.Context, arg MarcarEstornoParams) (int64, error) {
	result, err := q.db.Exec(ctx, marcarEstorno,
		arg.Motivo,
		arg.Agora,
		arg.ID,
		arg.De,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pedidoOperador = `-- name: PedidoOperador :many
SELECT id, sessao_id, email, assentos::text[] AS assentos, total_centavos, status, motivo_estorno, criado_em
FROM pedidos
WHERE id = $1
`

type PedidoOperadorRow struct {
	ID            uuid.UUID `db:"id"`
	SessaoID      int64     `db:"sessao_id"`
	Email         string    `db:"email"`
	Assentos      []string  `db:"assentos"`
	TotalCentavos int64     `db:"total_centavos"`
	Status        string    `db:"status"`
	MotivoEstorno *string   `db:"motivo_estorno"`
	CriadoEm      time.Time `db:"criado_em"`
}

func (q *Queries) PedidoOperador(ctx context.Context, id uuid.UUID) ([]PedidoOperadorRow, error) {
	rows, err := q.db.Query(ctx, pedidoOperador, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PedidoOperadorRow
	for rows.Next() {
		var i PedidoOperadorRow
		if err := rows.Scan(
			&i.ID,
			&i.SessaoID,
			&i.Email,
			&i.Assentos,
			&i.TotalCentavos,
			&i.Status,
			&i.MotivoEstorno,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pedidoParaNotificacao = `-- name: PedidoParaNotificacao :many
SELECT status, email, codigo, sessao_id, total_centavos
FROM pedidos
WHERE id = $1
`

type PedidoParaNotificacaoRow struct {
	Status        string `db:"status"`
	Email         string `db:"email"`
	Codigo        string `db:"codigo"`
	SessaoID      int64  `db:"sessao_id"`
	TotalCentavos int64  `db:"total_centavos"`
}

// Porta da notificação (PRD 0028): o e-mail sai só de pedido pago.
func (q *Queries) PedidoParaNotificacao(ctx context.Context, id uuid.UUID) ([]PedidoParaNotificacaoRow, error) {
	rows, err := q.db.Query(ctx, pedidoParaNotificacao, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PedidoParaNotificacaoRow
	for rows.Next() {
		var i PedidoParaNotificacaoRow
		if err := rows.Scan(
			&i.Status,
			&i.Email,
			&i.Codigo,
			&i.SessaoID,
			&i.TotalCentavos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pedidoPorCodigo = `-- name: PedidoPorCodigo :many
SELECT id, email, codigo, sessao_id, assentos::text[] AS assentos, total_centavos, status, expira_em
FROM pedidos
WHERE codigo = $1
`

type PedidoPorCodigoRow struct {
	ID            uuid.UUID `db:"id"`
	Email         string    `db:"email"`
	Codigo        string    `db:"codigo"`
	SessaoID      int64     `db:"sessao_id"`
	Assentos      []string  `db:"assentos"`
	TotalCentavos int64     `db:"total_centavos"`
	Status        string    `db:"status"`
	ExpiraEm      time.Time `db:"expira_em"`
}

// Consulta de convidado (PRD 0034): o código é único; o e-mail é conferido
// fora do SQL, em tempo constante, pelo mesmo caminho do "não encontrado".
func (q *Queries) PedidoPorCodigo(ctx context.Context, codigo string) ([]PedidoPorCodigoRow, error) {
	rows, err := q.db.Query(ctx, pedidoPorCodigo, codigo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PedidoPorCodigoRow
	for rows.Next() {
		var i PedidoPorCodigoRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Codigo,
			&i.SessaoID,
			&i.Assentos,
			&i.TotalCentavos,
			&i.Status,
			&i.ExpiraEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pedidosVencidos = `-- name: PedidosVencidos :many
SELECT id, payment_intent_id
FROM pedidos
WHERE status = 'aguardando_pagamento' AND expira_em <= $1
ORDER BY expira_em
LIMIT $2::int
`

type PedidosVencidosParams struct {
	Agora  time.Time `db:"agora"`
	Limite int32     `db:"limite"`
}

type PedidosVencidosRow struct {
	ID              uuid.UUID `db:"id"`
	PaymentIntentID *string   `db:"payment_intent_id"`
}

// Reconciliação (PRD 0025): pendentes cujo prazo passou, mais antigos antes.
func (q *Queries) PedidosVencidos(ctx context.Context, arg PedidosVencidosParams) ([]PedidosVencidosRow, error) {
	rows, err := q.db.Query(ctx, pedidosVencidos, arg.Agora, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PedidosVencidosRow
	for rows.Next() {
		var i PedidosVencidosRow
		if err := rows.Scan(&i.ID, &i.PaymentIntentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendenteDoDono = `-- name: PendenteDoDono :many
SELECT id, expira_em, payment_intent_id
FROM pedidos
WHERE dono_hash = $1 AND status = 'aguardando_pagamento'
`

type PendenteDoDonoRow struct {
	ID              uuid.UUID `db:"id"`
	ExpiraEm        time.Time `db:"expira_em"`
	PaymentIntentID *string   `db:"payment_intent_id"`
}

func (q *Queries) PendenteDoDono(ctx context.Context, donoHash []byte) ([]PendenteDoDonoRow, error) {
	rows, err := q.db.Query(ctx, pendenteDoDono, donoHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendenteDoDonoRow
	for rows.Next() {
		var i PendenteDoDonoRow
		if err := rows.Scan(&i.ID, &i.ExpiraEm, &i.PaymentIntentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendenteParaRetomar = `-- name: PendenteParaRetomar :many
SELECT status, expira_em, payment_intent_id, total_centavos, codigo
FROM pedidos
WHERE id = $1 AND dono_hash = $2
`

type PendenteParaRetomarParams struct {
	ID       uuid.UUID `db:"id"`
	DonoHash []byte    `db:"dono_hash"`
}

type PendenteParaRetomarRow struct {
	Status          string    `db:"status"`
	ExpiraEm        time.Time `db:"expira_em"`
	PaymentIntentID *string   `db:"payment_intent_id"`
	TotalCentavos   int64     `db:"total_centavos"`
	Codigo          string    `db:"codigo"`
}

// Retomada do pagamento (PRD 0031): só o carrinho dono, com a cobrança.
func (q *Queries) PendenteParaRetomar(ctx context.Context, arg PendenteParaRetomarParams) ([]PendenteParaRetomarRow, error) {
	rows, err := q.db.Query(ctx, pendenteParaRetomar, arg.ID, arg.DonoHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendenteParaRetomarRow
	for rows.Next() {
		var i PendenteParaRetomarRow
		if err := rows.Scan(
			&i.Status,
			&i.ExpiraEm,
			&i.PaymentIntentID,
			&i.TotalCentavos,
			&i.Codigo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarEvento = `-- name: RegistrarEvento :exec
INSERT INTO pedido_eventos (pedido_id, de, para, ocorrido_em)
VALUES ($1, $2, $3, $4)
`

type RegistrarEventoParams struct {
	PedidoID uuid.UUID `db:"pedido_id"`
	De       *string   `db:"de"`
	Para     string    `db:"para"`
	Agora    time.Time `db:"agora"`
}

// Trilha append-only das transições (só IDs e estados).
func (q *Queries) RegistrarEvento(ctx context.Context, arg RegistrarEventoParams) error {
	_, err := q.db.Exec(ctx, registrarEvento,
		arg.PedidoID,
		arg.De,
		arg.Para,
		arg.Agora,
	)
	return err
}

const registrarEventoStripe = `-- name: RegistrarEventoStripe :many
INSERT INTO stripe_eventos (event_id, tipo, recebido_em)
VALUES ($1, $2, $3)
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id
`

type RegistrarEventoStripeParams struct {
	EventID string    `db:"event_id"`
	Tipo    string    `db:"tipo"`
	Agora   time.Time `db:"agora"`
}

// Dedup do webhook na TX do efeito: sem linha no RETURNING = já processado.
func (q *Queries) RegistrarEventoStripe(ctx context.Context, arg RegistrarEventoStripeParams) ([]string, error) {
	rows, err := q.db.Query(ctx, registrarEventoStripe, arg.EventID, arg.Tipo, arg.Agora)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var event_id string
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarFalhaEstorno = `-- name: RegistrarFalhaEstorno :execrows
UPDATE pedidos
SET tentativas_estorno = tentativas_estorno + 1, atualizado_em = $1
WHERE id = $2 AND status = 'estorno_pendente'
`

type RegistrarFalhaEstornoParams struct {
	Agora time.Time `db:"agora"`
	ID    uuid.UUID `db:"id"`
}

func (q *Queries) RegistrarFalhaEstorno(ctx context.Context, arg RegistrarFalhaEstornoParams) (int64, error) {
	result, err := q.db.Exec(ctx, registrarFalhaEstorno, arg.Agora, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transicionar = `-- name: Transicionar :execrows
UPDATE pedidos
SET status = $1, atualizado_em = $2
WHERE id = $3 AND status = $4
`

type TransicionarParams struct {
	Para  string    `db:"para"`
	Agora time.Time `db:"agora"`
	ID    uuid.UUID `db:"id"`
	De    string    `db:"de"`
}

// Compare-and-swap (ADR 0005/0010): só transiciona a partir do estado lido.
// Zero linhas = outro caminho já transicionou (corrida perdida).
func (q *Queries) Transicionar(ctx context.Context, arg TransicionarParams) (int64, error) {
	result, err := q.db.Exec(ctx, transicionar,
		arg.Para,
		arg.Agora,
		arg.ID,
		arg.De,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const travarParaCancelar = `-- name: TravarParaCancelar :many
SELECT p.id, p.sessao_id, p.status, p.usuario_id,
       EXISTS (SELECT 1 FROM ingressos i WHERE i.pedido_id = p.id AND i.status = 'usado') AS tem_usado
FROM pedidos p
WHERE p.id = $1
FOR UPDATE OF p
`

type TravarParaCancelarRow struct {
	ID        uuid.UUID  `db:"id"`
	SessaoID  int64      `db:"sessao_id"`
	Status    string     `db:"status"`
	UsuarioID *uuid.UUID `db:"usuario_id"`
	TemUsado  bool       `db:"tem_usado"`
}

// Cancelamento (PRD 0036): trava o pedido e diz se algum ingresso já foi usado.
func (q *Queries) TravarParaCancelar(ctx context.Context, id uuid.UUID) ([]TravarParaCancelarRow, error) {
	rows, err := q.db.Query(ctx, travarParaCancelar, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TravarParaCancelarRow
	for rows.Next() {
		var i TravarParaCancelarRow
		if err := rows.Scan(
			&i.ID,
			&i.SessaoID,
			&i.Status,
			&i.UsuarioID,
			&i.TemUsado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const travarPedido = `-- name: TravarPedido :many
SELECT id, sessao_id, assentos::text[] AS assentos, total_centavos, status, payment_intent_id
FROM pedidos
WHERE id = $1
FOR UPDATE
`

type TravarPedidoRow struct {
	ID              uuid.UUID `db:"id"`
	SessaoID        int64     `db:"sessao_id"`
	Assentos        []string  `db:"assentos"`
	TotalCentavos   int64     `db:"total_centavos"`
	Status          string    `db:"status"`
	PaymentIntentID *string   `db:"payment_intent_id"`
}

// Pivô (ADR 0010): a linha do pedido fica travada até o fim da TX.
func (q *Queries) TravarPedido(ctx context.Context, id uuid.UUID) ([]TravarPedidoRow, error) {
	rows, err := q.db.Query(ctx, travarPedido, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TravarPedidoRow
	for rows.Next() {
		var i TravarPedidoRow
		if err := rows.Scan(
			&i.ID,
			&i.SessaoID,
			&i.Assentos,
			&i.TotalCentavos,
			&i.Status,
			&i.PaymentIntentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const travarPedidosDaSessao = `-- name: TravarPedidosDaSessao :many
SELECT id, status
FROM pedidos
WHERE sessao_id = $1
ORDER BY id
FOR UPDATE
`

type TravarPedidosDaSessaoRow struct {
	ID     uuid.UUID `db:"id"`
	Status string    `db:"status"`
}

// Cancelamento da sessão (PRD 0036 RF11): trava TODOS os pedidos da sessão
// (ordem fixa contra deadlock) — um pivô em curso termina antes.
func (q *Queries) TravarPedidosDaSessao(ctx context.Context, sessaoID int64) ([]TravarPedidosDaSessaoRow, error) {
	rows, err := q.db.Query(ctx, travarPedidosDaSessao, sessaoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TravarPedidosDaSessaoRow
	for rows.Next() {
		var i TravarPedidosDaSessaoRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
