// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const buscarPedidoDoDono = `-- name: BuscarPedidoDoDono :many
SELECT id, codigo, sessao_id, assentos::text[] AS assentos, total_centavos, status, expira_em
FROM pedidos
WHERE id = $1 AND dono_hash = $2
`

type BuscarPedidoDoDonoParams struct {
	ID       uuid.UUID `db:"id"`
	DonoHash []byte    `db:"dono_hash"`
}

type BuscarPedidoDoDonoRow struct {
	ID            uuid.UUID `db:"id"`
	Codigo        string    `db:"codigo"`
	SessaoID      int64     `db:"sessao_id"`
	Assentos      []string  `db:"assentos"`
	TotalCentavos int64     `db:"total_centavos"`
	Status        string    `db:"status"`
	ExpiraEm      time.Time `db:"expira_em"`
}

// Posse (RF06): só o carrinho que criou o pedido o enxerga.
func (q *Queries) BuscarPedidoDoDono(ctx context.Context, arg BuscarPedidoDoDonoParams) ([]BuscarPedidoDoDonoRow, error) {
	rows, err := q.db.Query(ctx, buscarPedidoDoDono, arg.ID, arg.DonoHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarPedidoDoDonoRow
	for rows.Next() {
		var i BuscarPedidoDoDonoRow
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.SessaoID,
			&i.Assentos,
			&i.TotalCentavos,
			&i.Status,
			&i.ExpiraEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const definirCobranca = `-- name: DefinirCobranca :execrows
UPDATE pedidos
SET payment_intent_id = $1, atualizado_em = $2
WHERE id = $3 AND status = 'aguardando_pagamento' AND payment_intent_id IS NULL
`

type DefinirCobrancaParams struct {
	PaymentIntentID *string   `db:"payment_intent_id"`
	Agora           time.Time `db:"agora"`
	ID              uuid.UUID `db:"id"`
}

// Grava o id da cobrança do gateway enquanto o pedido espera pagamento.
func (q *Queries) DefinirCobranca(ctx context.Context, arg DefinirCobrancaParams) (int64, error) {
	result, err := q.db.Exec(ctx, definirCobranca, arg.PaymentIntentID, arg.Agora, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const inserirPedido = `-- name: InserirPedido :many
INSERT INTO pedidos (id, codigo, email, dono_hash, sessao_id, assentos, total_centavos, status, expira_em, criado_em, atualizado_em)
VALUES ($1, $2, $3, $4, $5, $6::varchar[], $7, 'aguardando_pagamento', $8, $9, $9)
ON CONFLICT (dono_hash) WHERE status = 'aguardando_pagamento' DO NOTHING
RETURNING id
`

type InserirPedidoParams struct {
	ID            uuid.UUID `db:"id"`
	Codigo        string    `db:"codigo"`
	Email         string    `db:"email"`
	DonoHash      []byte    `db:"dono_hash"`
	SessaoID      int64     `db:"sessao_id"`
	Assentos      []string  `db:"assentos"`
	TotalCentavos int64     `db:"total_centavos"`
	ExpiraEm      time.Time `db:"expira_em"`
	Agora         time.Time `db:"agora"`
}

// Sem linha no RETURNING = o carrinho já tem pedido pendente (índice único
// parcial pedidos_pendente_por_dono) — decidido pelo banco, sem pré-check.
func (q *Queries) InserirPedido(ctx context.Context, arg InserirPedidoParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, inserirPedido,
		arg.ID,
		arg.Codigo,
		arg.Email,
		arg.DonoHash,
		arg.SessaoID,
		arg.Assentos,
		arg.TotalCentavos,
		arg.ExpiraEm,
		arg.Agora,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendenteDoDono = `-- name: PendenteDoDono :many
SELECT id, expira_em
FROM pedidos
WHERE dono_hash = $1 AND status = 'aguardando_pagamento'
`

type PendenteDoDonoRow struct {
	ID       uuid.UUID `db:"id"`
	ExpiraEm time.Time `db:"expira_em"`
}

func (q *Queries) PendenteDoDono(ctx context.Context, donoHash []byte) ([]PendenteDoDonoRow, error) {
	rows, err := q.db.Query(ctx, pendenteDoDono, donoHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendenteDoDonoRow
	for rows.Next() {
		var i PendenteDoDonoRow
		if err := rows.Scan(&i.ID, &i.ExpiraEm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarEvento = `-- name: RegistrarEvento :exec
INSERT INTO pedido_eventos (pedido_id, de, para, ocorrido_em)
VALUES ($1, $2, $3, $4)
`

type RegistrarEventoParams struct {
	PedidoID uuid.UUID `db:"pedido_id"`
	De       *string   `db:"de"`
	Para     string    `db:"para"`
	Agora    time.Time `db:"agora"`
}

// Trilha append-only das transições (só IDs e estados).
func (q *Queries) RegistrarEvento(ctx context.Context, arg RegistrarEventoParams) error {
	_, err := q.db.Exec(ctx, registrarEvento,
		arg.PedidoID,
		arg.De,
		arg.Para,
		arg.Agora,
	)
	return err
}

const transicionar = `-- name: Transicionar :execrows
UPDATE pedidos
SET status = $1, atualizado_em = $2
WHERE id = $3 AND status = $4
`

type TransicionarParams struct {
	Para  string    `db:"para"`
	Agora time.Time `db:"agora"`
	ID    uuid.UUID `db:"id"`
	De    string    `db:"de"`
}

// Compare-and-swap (ADR 0005/0010): só transiciona a partir do estado lido.
// Zero linhas = outro caminho já transicionou (corrida perdida).
func (q *Queries) Transicionar(ctx context.Context, arg TransicionarParams) (int64, error) {
	result, err := q.db.Exec(ctx, transicionar,
		arg.Para,
		arg.Agora,
		arg.ID,
		arg.De,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
