// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"
)

type Filme struct {
	ID           int64      `db:"id"`
	Titulo       string     `db:"titulo"`
	Ano          *int32     `db:"ano"`
	DuracaoMin   *int32     `db:"duracao_min"`
	Sinopse      *string    `db:"sinopse"`
	ImdbID       *string    `db:"imdb_id"`
	PosterUrl    *string    `db:"poster_url"`
	CriadoEm     time.Time  `db:"criado_em"`
	TmdbID       *int64     `db:"tmdb_id"`
	ArquivadoEm  *time.Time `db:"arquivado_em"`
	AtualizadoEm time.Time  `db:"atualizado_em"`
}

type Sala struct {
	ID           int64           `db:"id"`
	Nome         string          `db:"nome"`
	Layout       json.RawMessage `db:"layout"`
	CriadoEm     time.Time       `db:"criado_em"`
	AtualizadoEm time.Time       `db:"atualizado_em"`
}

type Sesso struct {
	ID            int64     `db:"id"`
	FilmeID       int64     `db:"filme_id"`
	SalaID        int64     `db:"sala_id"`
	Inicio        time.Time `db:"inicio"`
	DuracaoMin    int32     `db:"duracao_min"`
	Fim           time.Time `db:"fim"`
	PrecoCentavos int32     `db:"preco_centavos"`
	Status        string    `db:"status"`
	CriadoEm      time.Time `db:"criado_em"`
	AtualizadoEm  time.Time `db:"atualizado_em"`
}
