// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const atualizarSala = `-- name: AtualizarSala :many
UPDATE salas SET nome = $2, layout = $3, atualizado_em = now()
WHERE id = $1
RETURNING id, nome, layout
`

type AtualizarSalaParams struct {
	ID     int64           `db:"id"`
	Nome   string          `db:"nome"`
	Layout json.RawMessage `db:"layout"`
}

type AtualizarSalaRow struct {
	ID     int64           `db:"id"`
	Nome   string          `db:"nome"`
	Layout json.RawMessage `db:"layout"`
}

func (q *Queries) AtualizarSala(ctx context.Context, arg AtualizarSalaParams) ([]AtualizarSalaRow, error) {
	rows, err := q.db.Query(ctx, atualizarSala, arg.ID, arg.Nome, arg.Layout)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtualizarSalaRow
	for rows.Next() {
		var i AtualizarSalaRow
		if err := rows.Scan(&i.ID, &i.Nome, &i.Layout); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarSala = `-- name: BuscarSala :many
SELECT id, nome, layout FROM salas WHERE id = $1 LIMIT 1
`

type BuscarSalaRow struct {
	ID     int64           `db:"id"`
	Nome   string          `db:"nome"`
	Layout json.RawMessage `db:"layout"`
}

// :many + LIMIT 1: ausência = vazio (domínio sem pgx.ErrNoRows).
func (q *Queries) BuscarSala(ctx context.Context, id int64) ([]BuscarSalaRow, error) {
	rows, err := q.db.Query(ctx, buscarSala, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarSalaRow
	for rows.Next() {
		var i BuscarSalaRow
		if err := rows.Scan(&i.ID, &i.Nome, &i.Layout); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelarSessao = `-- name: CancelarSessao :execrows
UPDATE sessoes SET status = 'cancelada', atualizado_em = now() WHERE id = $1
`

// Idempotente; 0 linhas = inexistente. A cancelada sai da EXCLUDE.
func (q *Queries) CancelarSessao(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, cancelarSessao, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existeSessaoFuturaNaSala = `-- name: ExisteSessaoFuturaNaSala :one
SELECT EXISTS (
    SELECT 1 FROM sessoes WHERE sala_id = $1 AND status = 'agendada' AND fim > $2
) AS existe
`

type ExisteSessaoFuturaNaSalaParams struct {
	SalaID int64     `db:"sala_id"`
	Fim    time.Time `db:"fim"`
}

// Imutabilidade do layout (RN03 do PRD 0013): sessão agendada ainda por vir.
func (q *Queries) ExisteSessaoFuturaNaSala(ctx context.Context, arg ExisteSessaoFuturaNaSalaParams) (bool, error) {
	row := q.db.QueryRow(ctx, existeSessaoFuturaNaSala, arg.SalaID, arg.Fim)
	var existe bool
	err := row.Scan(&existe)
	return existe, err
}

const inserirSala = `-- name: InserirSala :one
INSERT INTO salas (nome, layout) VALUES ($1, $2)
RETURNING id, nome, layout
`

type InserirSalaParams struct {
	Nome   string          `db:"nome"`
	Layout json.RawMessage `db:"layout"`
}

type InserirSalaRow struct {
	ID     int64           `db:"id"`
	Nome   string          `db:"nome"`
	Layout json.RawMessage `db:"layout"`
}

func (q *Queries) InserirSala(ctx context.Context, arg InserirSalaParams) (InserirSalaRow, error) {
	row := q.db.QueryRow(ctx, inserirSala, arg.Nome, arg.Layout)
	var i InserirSalaRow
	err := row.Scan(&i.ID, &i.Nome, &i.Layout)
	return i, err
}

const inserirSessao = `-- name: InserirSessao :one
INSERT INTO sessoes (filme_id, sala_id, inicio, duracao_min, fim, preco_centavos)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, filme_id, sala_id, inicio, duracao_min, fim, preco_centavos, status
`

type InserirSessaoParams struct {
	FilmeID       int64     `db:"filme_id"`
	SalaID        int64     `db:"sala_id"`
	Inicio        time.Time `db:"inicio"`
	DuracaoMin    int32     `db:"duracao_min"`
	Fim           time.Time `db:"fim"`
	PrecoCentavos int32     `db:"preco_centavos"`
}

type InserirSessaoRow struct {
	ID            int64     `db:"id"`
	FilmeID       int64     `db:"filme_id"`
	SalaID        int64     `db:"sala_id"`
	Inicio        time.Time `db:"inicio"`
	DuracaoMin    int32     `db:"duracao_min"`
	Fim           time.Time `db:"fim"`
	PrecoCentavos int32     `db:"preco_centavos"`
	Status        string    `db:"status"`
}

// A EXCLUDE sessoes_sem_conflito rejeita sobreposição (23P01 → 409).
func (q *Queries) InserirSessao(ctx context.Context, arg InserirSessaoParams) (InserirSessaoRow, error) {
	row := q.db.QueryRow(ctx, inserirSessao,
		arg.FilmeID,
		arg.SalaID,
		arg.Inicio,
		arg.DuracaoMin,
		arg.Fim,
		arg.PrecoCentavos,
	)
	var i InserirSessaoRow
	err := row.Scan(
		&i.ID,
		&i.FilmeID,
		&i.SalaID,
		&i.Inicio,
		&i.DuracaoMin,
		&i.Fim,
		&i.PrecoCentavos,
		&i.Status,
	)
	return i, err
}

const listarSalas = `-- name: ListarSalas :many
SELECT id, nome, layout FROM salas ORDER BY nome LIMIT 200
`

type ListarSalasRow struct {
	ID     int64           `db:"id"`
	Nome   string          `db:"nome"`
	Layout json.RawMessage `db:"layout"`
}

func (q *Queries) ListarSalas(ctx context.Context) ([]ListarSalasRow, error) {
	rows, err := q.db.Query(ctx, listarSalas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarSalasRow
	for rows.Next() {
		var i ListarSalasRow
		if err := rows.Scan(&i.ID, &i.Nome, &i.Layout); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSessoesBackoffice = `-- name: ListarSessoesBackoffice :many
SELECT id, filme_id, sala_id, inicio, duracao_min, fim, preco_centavos, status
FROM sessoes
ORDER BY inicio DESC
LIMIT 200
`

type ListarSessoesBackofficeRow struct {
	ID            int64     `db:"id"`
	FilmeID       int64     `db:"filme_id"`
	SalaID        int64     `db:"sala_id"`
	Inicio        time.Time `db:"inicio"`
	DuracaoMin    int32     `db:"duracao_min"`
	Fim           time.Time `db:"fim"`
	PrecoCentavos int32     `db:"preco_centavos"`
	Status        string    `db:"status"`
}

func (q *Queries) ListarSessoesBackoffice(ctx context.Context) ([]ListarSessoesBackofficeRow, error) {
	rows, err := q.db.Query(ctx, listarSessoesBackoffice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarSessoesBackofficeRow
	for rows.Next() {
		var i ListarSessoesBackofficeRow
		if err := rows.Scan(
			&i.ID,
			&i.FilmeID,
			&i.SalaID,
			&i.Inicio,
			&i.DuracaoMin,
			&i.Fim,
			&i.PrecoCentavos,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessaoConflitante = `-- name: SessaoConflitante :many
SELECT id, inicio, fim FROM sessoes
WHERE sala_id = $1 AND status = 'agendada'
  AND tstzrange(inicio, fim, '[)') && tstzrange($2::timestamptz, $3::timestamptz, '[)')
ORDER BY inicio
LIMIT 1
`

type SessaoConflitanteParams struct {
	SalaID int64     `db:"sala_id"`
	Inicio time.Time `db:"inicio"`
	Fim    time.Time `db:"fim"`
}

type SessaoConflitanteRow struct {
	ID     int64     `db:"id"`
	Inicio time.Time `db:"inicio"`
	Fim    time.Time `db:"fim"`
}

// Reconsulta após o 23P01 para devolver o horário conflitante no 409.
func (q *Queries) SessaoConflitante(ctx context.Context, arg SessaoConflitanteParams) ([]SessaoConflitanteRow, error) {
	rows, err := q.db.Query(ctx, sessaoConflitante, arg.SalaID, arg.Inicio, arg.Fim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessaoConflitanteRow
	for rows.Next() {
		var i SessaoConflitanteRow
		if err := rows.Scan(&i.ID, &i.Inicio, &i.Fim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
