// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Hold struct {
	ID              uuid.UUID  `db:"id"`
	SessaoID        int64      `db:"sessao_id"`
	AssentoCodigo   string     `db:"assento_codigo"`
	DonoHash        []byte     `db:"dono_hash"`
	Status          string     `db:"status"`
	ExpiresAt       time.Time  `db:"expires_at"`
	ExtensoesUsadas int16      `db:"extensoes_usadas"`
	CriadoEm        time.Time  `db:"criado_em"`
	AtualizadoEm    time.Time  `db:"atualizado_em"`
	PedidoID        *uuid.UUID `db:"pedido_id"`
}
