// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const buscarHoldVivoDoDono = `-- name: BuscarHoldVivoDoDono :many
SELECT id, sessao_id, assento_codigo, expires_at, extensoes_usadas
FROM holds
WHERE id = $1 AND dono_hash = $2 AND status = 'ativo' AND expires_at > $3
`

type BuscarHoldVivoDoDonoParams struct {
	ID       uuid.UUID `db:"id"`
	DonoHash []byte    `db:"dono_hash"`
	Agora    time.Time `db:"agora"`
}

type BuscarHoldVivoDoDonoRow struct {
	ID              uuid.UUID `db:"id"`
	SessaoID        int64     `db:"sessao_id"`
	AssentoCodigo   string    `db:"assento_codigo"`
	ExpiresAt       time.Time `db:"expires_at"`
	ExtensoesUsadas int16     `db:"extensoes_usadas"`
}

func (q *Queries) BuscarHoldVivoDoDono(ctx context.Context, arg BuscarHoldVivoDoDonoParams) ([]BuscarHoldVivoDoDonoRow, error) {
	rows, err := q.db.Query(ctx, buscarHoldVivoDoDono, arg.ID, arg.DonoHash, arg.Agora)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarHoldVivoDoDonoRow
	for rows.Next() {
		var i BuscarHoldVivoDoDonoRow
		if err := rows.Scan(
			&i.ID,
			&i.SessaoID,
			&i.AssentoCodigo,
			&i.ExpiresAt,
			&i.ExtensoesUsadas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const estenderHold = `-- name: EstenderHold :many
UPDATE holds
SET expires_at = $1, extensoes_usadas = extensoes_usadas + 1, atualizado_em = $2
WHERE id = $3 AND dono_hash = $4 AND status = 'ativo' AND expires_at > $2 AND extensoes_usadas = 0
RETURNING id, sessao_id, assento_codigo, expires_at, extensoes_usadas
`

type EstenderHoldParams struct {
	NovoExpiresAt time.Time `db:"novo_expires_at"`
	Agora         time.Time `db:"agora"`
	ID            uuid.UUID `db:"id"`
	DonoHash      []byte    `db:"dono_hash"`
}

type EstenderHoldRow struct {
	ID              uuid.UUID `db:"id"`
	SessaoID        int64     `db:"sessao_id"`
	AssentoCodigo   string    `db:"assento_codigo"`
	ExpiresAt       time.Time `db:"expires_at"`
	ExtensoesUsadas int16     `db:"extensoes_usadas"`
}

// Guarda da extensão única (última linha de defesa; o aggregate é a primeira).
func (q *Queries) EstenderHold(ctx context.Context, arg EstenderHoldParams) ([]EstenderHoldRow, error) {
	rows, err := q.db.Query(ctx, estenderHold,
		arg.NovoExpiresAt,
		arg.Agora,
		arg.ID,
		arg.DonoHash,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EstenderHoldRow
	for rows.Next() {
		var i EstenderHoldRow
		if err := rows.Scan(
			&i.ID,
			&i.SessaoID,
			&i.AssentoCodigo,
			&i.ExpiresAt,
			&i.ExtensoesUsadas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expirarVencidos = `-- name: ExpirarVencidos :execrows
UPDATE holds
SET status = 'expirado', atualizado_em = $1
WHERE id IN (
    SELECT h.id FROM holds h
    WHERE h.status = 'ativo' AND h.expires_at <= $1
    ORDER BY h.expires_at
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
)
`

type ExpirarVencidosParams struct {
	Agora  time.Time `db:"agora"`
	Limite int32     `db:"limite"`
}

// Higiene (o roubo não depende disto): lote limitado, sem esperar linhas que
// uma trava concorrente esteja roubando.
func (q *Queries) ExpirarVencidos(ctx context.Context, arg ExpirarVencidosParams) (int64, error) {
	result, err := q.db.Exec(ctx, expirarVencidos, arg.Agora, arg.Limite)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const holdsVivosDoDono = `-- name: HoldsVivosDoDono :many
SELECT id, sessao_id, assento_codigo, expires_at, extensoes_usadas
FROM holds
WHERE dono_hash = $1 AND status = 'ativo' AND expires_at > $2
ORDER BY expires_at, sessao_id, assento_codigo
`

type HoldsVivosDoDonoParams struct {
	DonoHash []byte    `db:"dono_hash"`
	Agora    time.Time `db:"agora"`
}

type HoldsVivosDoDonoRow struct {
	ID              uuid.UUID `db:"id"`
	SessaoID        int64     `db:"sessao_id"`
	AssentoCodigo   string    `db:"assento_codigo"`
	ExpiresAt       time.Time `db:"expires_at"`
	ExtensoesUsadas int16     `db:"extensoes_usadas"`
}

func (q *Queries) HoldsVivosDoDono(ctx context.Context, arg HoldsVivosDoDonoParams) ([]HoldsVivosDoDonoRow, error) {
	rows, err := q.db.Query(ctx, holdsVivosDoDono, arg.DonoHash, arg.Agora)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HoldsVivosDoDonoRow
	for rows.Next() {
		var i HoldsVivosDoDonoRow
		if err := rows.Scan(
			&i.ID,
			&i.SessaoID,
			&i.AssentoCodigo,
			&i.ExpiresAt,
			&i.ExtensoesUsadas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liberarHold = `-- name: LiberarHold :execrows
UPDATE holds
SET status = 'liberado', atualizado_em = $1
WHERE id = $2 AND dono_hash = $3 AND status = 'ativo' AND expires_at > $1
`

type LiberarHoldParams struct {
	Agora    time.Time `db:"agora"`
	ID       uuid.UUID `db:"id"`
	DonoHash []byte    `db:"dono_hash"`
}

func (q *Queries) LiberarHold(ctx context.Context, arg LiberarHoldParams) (int64, error) {
	result, err := q.db.Exec(ctx, liberarHold, arg.Agora, arg.ID, arg.DonoHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tentarTravaSweeper = `-- name: TentarTravaSweeper :one
SELECT pg_try_advisory_xact_lock($1::int, $2::int) AS obtido
`

type TentarTravaSweeperParams struct {
	Namespace int32 `db:"namespace"`
	Chave     int32 `db:"chave"`
}

// Uma passada do sweeper por vez entre processos (worker e all).
func (q *Queries) TentarTravaSweeper(ctx context.Context, arg TentarTravaSweeperParams) (bool, error) {
	row := q.db.QueryRow(ctx, tentarTravaSweeper, arg.Namespace, arg.Chave)
	var obtido bool
	err := row.Scan(&obtido)
	return obtido, err
}

const travarAssento = `-- name: TravarAssento :many
INSERT INTO holds (id, sessao_id, assento_codigo, dono_hash, status, expires_at, extensoes_usadas, criado_em, atualizado_em)
VALUES ($1, $2, $3, $4, 'ativo', $5, 0, $6, $6)
ON CONFLICT (sessao_id, assento_codigo) WHERE status = 'ativo'
DO UPDATE SET id = EXCLUDED.id, dono_hash = EXCLUDED.dono_hash, expires_at = EXCLUDED.expires_at,
    extensoes_usadas = 0, criado_em = EXCLUDED.criado_em, atualizado_em = EXCLUDED.atualizado_em
WHERE holds.expires_at <= $6
RETURNING id, sessao_id, assento_codigo, expires_at, extensoes_usadas
`

type TravarAssentoParams struct {
	ID            uuid.UUID `db:"id"`
	SessaoID      int64     `db:"sessao_id"`
	AssentoCodigo string    `db:"assento_codigo"`
	DonoHash      []byte    `db:"dono_hash"`
	ExpiresAt     time.Time `db:"expires_at"`
	Agora         time.Time `db:"agora"`
}

type TravarAssentoRow struct {
	ID              uuid.UUID `db:"id"`
	SessaoID        int64     `db:"sessao_id"`
	AssentoCodigo   string    `db:"assento_codigo"`
	ExpiresAt       time.Time `db:"expires_at"`
	ExtensoesUsadas int16     `db:"extensoes_usadas"`
}

// Único caminho de criação (ADR 0008): cria o hold ou rouba um vencido.
// Sem linha no RETURNING = hold vivo de outro dono → 409.
func (q *Queries) TravarAssento(ctx context.Context, arg TravarAssentoParams) ([]TravarAssentoRow, error) {
	rows, err := q.db.Query(ctx, travarAssento,
		arg.ID,
		arg.SessaoID,
		arg.AssentoCodigo,
		arg.DonoHash,
		arg.ExpiresAt,
		arg.Agora,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TravarAssentoRow
	for rows.Next() {
		var i TravarAssentoRow
		if err := rows.Scan(
			&i.ID,
			&i.SessaoID,
			&i.AssentoCodigo,
			&i.ExpiresAt,
			&i.ExtensoesUsadas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const travarDono = `-- name: TravarDono :exec
SELECT pg_advisory_xact_lock($1::int, $2::int)
`

type TravarDonoParams struct {
	Namespace int32 `db:"namespace"`
	Chave     int32 `db:"chave"`
}

// Serializa as TXs de trava do MESMO dono (teto de holds — ADR 0008); solta
// sozinho no commit/rollback.
func (q *Queries) TravarDono(ctx context.Context, arg TravarDonoParams) error {
	_, err := q.db.Exec(ctx, travarDono, arg.Namespace, arg.Chave)
	return err
}
